### ISSUE TITLE
feature request: use `<a>` for pane buttons

### ISSUE THREAD

**Issue by scarf005** [rlane/oort3#13]
# Summary

![image](https://github.com/rlane/oort3/assets/54838975/91dfd376-bc83-4586-8063-80b47e1556b1)

hi, great game!
currently pane buttons are `<span>`, and converting it into `<a>` will make it easier to navigate with keyboard using [vimium](https://github.com/philc/vimium).

## Screenshots

![image](https://github.com/rlane/oort3/assets/54838975/66711906-66be-4583-8d47-2c4fe5632d39)
![image](https://github.com/rlane/oort3/assets/54838975/3f65223f-b677-47ce-b64d-8caa3686f888)

**Comment by rlane** [comment]
The buttons are created by the GoldenLayout library, so after looking at https://github.com/philc/vimium/blob/31af27bb9c362792bc531df8b0865dfb87afa36b/content_scripts/link_hints.js#L1073 it was easiest to add role=tab to them after they're created.

I'll release this later today.
