### ISSUE TITLE
Possible translation

### ISSUE THREAD

**Issue by DoubleHyphen** [rlane/oort3#38]
Please bear in mind that I haven't yet found the time to read the source code fully. Thus, I thought I'd ask directly.

1. Is this game fully open-source? If so, will it stay that way?
2. Is it possible to translate this game to other languages?

Thank you in advance for your time and consideration.

**Comment by rlane** [comment]
Yes, the game is fully open source and I have no plans to change that.

The game currently is not capable of being translated. It would be quite some work to make that possible.
