### ISSUE TITLE
Error on compiling repo

### ISSUE THREAD

**Issue by nikitaservais** [rlane/oort3#41]
error[E0433]: failed to resolve: use of undeclared crate or module `wasmer_compiler_singlepass`
   --> shared/simulator/src/vm/mod.rs:261:36
    |
261 |         let mut store = Store::new(wasmer_compiler_singlepass::Singlepass::new());
    |                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `wasmer_compiler_singlepass`

For more information about this error, try `rustc --explain E0433`.
error: could not compile `oort_simulator` (lib) due to previous error

**Comment by rlane** [comment]
Which Rust version and operating system are you using?

What was the compile command you used? `cargo oort-serve` compiles and runs the app locally.

**Comment by nikitaservais** [comment]
I used cargo 1.71.0 (cfd3bbd8f 2023-06-08). 
macOS 14 (sonoma).
I used cargo oort-serve.

**Comment by nikitaservais** [comment]
Indeed thank you! 
ps: for those interested  [commit fix](https://github.com/rlane/oort3/commit/eed99790b720c0e559f41e16a37798f6f963f48a)
